studiometa/webpack-config

package-lock.json, package.json, packages/demo/package.json, packages/webpack-config/package.json, packages/webpack-config/src/webpack.base.config.js
- Fix a bug where ES6 features were used in the output files (b662a6a)
=> [Hotfix] 3.0.1

package-lock.json, package.json, packages/demo/package.json, packages/demo/src/templates/pages/index.twig, packages/webpack-config/package.json, packages/webpack-config/src/presets/prototyping.js, packages/webpack-config/src/utils/Html.js
- **Presets/Prototyping:** Add support for functions and tags from [studiometa/twig-toolkit](https://github.com/studiometa/twig-toolkit) (95b4f66)
- **Presets/Prototyping:** Fix a bug where dependencies paths were not absolute (7d6f468)
=> [Hotfix] 3.1.0 alpha.2

.github/workflows/release.yml, README.md, package-lock.json, package.json, packages/demo/package.json, packages/webpack-config/package.json, packages/webpack-config/src/presets/prototyping.js
- Add support for static assets (e8da906, d471927, 2ab6930)
- Fix custom Twig tag parsing (40faef6)
- Use relative paths for the Twig include comment helper (bc9bc79)
=> [Hotfix] 3.1.0 alpha.4

package-lock.json, package.json, packages/demo/package.json, packages/webpack-config/package.json
- Add a `defineConfig` function to improve configuration DX (70b5f34)
- Add support for `modern` and `legacy` targets (#37)
- Add support for `@studiometa/*` packages transpilation (#47)
- Add support for static assets in a `public` folder for the prototyping preset (#51) 
- Update dependencies
- Disable Webpack's future defaults options (3cca9b2)
=> [Release] 3.1.0

package-lock.json, package.json, packages/demo/package.json, packages/webpack-config/package.json, packages/webpack-config/src/utils/get-browsersync.js
- Fix logging information in dev mode (differentiate proxy vs access url)
- Fix support for latest ESLint and StyleLint versions
=> [Hotfix] 3.1.2

package-lock.json, package.json, packages/demo/package.json, packages/preset-vue-2/package.json, packages/preset-vue-3/package.json, packages/webpack-config/package.json, packages/webpack-config/src/utils/get-config.js
- ⚠️ **Breaking:** Change default target from legacy to modern (3ac83a8, #67)
=> [Hotfix] 4.0.0 alpha.1

package-lock.json, package.json, packages/demo/package.json, packages/preset-vue-2/package.json, packages/preset-vue-3/package.json, packages/webpack-config/package.json, packages/webpack-config/src/utils/Html.js
- Fix output of  Twig function `html_attributes` (af60b6c)
=> [Hotfix] 4.0.0 alpha.2

package-lock.json, package.json, packages/demo/package.json, packages/preset-vue-2/package.json, packages/preset-vue-3/package.json, packages/webpack-config/package.json
- Fix peer dependencies conflicts (78f8482)
=> [Hotfix] 4.0.1

README.md, packages/demo/meta.config.js, packages/webpack-config/src/presets/eslint.js, packages/webpack-config/src/presets/index.js, packages/webpack-config/src/presets/stylelint.js, packages/webpack-config/src/webpack.base.config.js
- Move linting plugins to presets (#79)
=> [Feature] Move linting plugins to presets

package-lock.json, package.json, packages/demo/package.json, packages/preset-vue-2/package.json, packages/preset-vue-3/package.json, packages/webpack-config/bin/cli.js, packages/webpack-config/package.json
- Print package version when starting a command (ea9462a)
=> [Hotfix] 4.0.3

composer.json, composer.lock, package-lock.json, package.json, packages/demo/package.json, packages/php/src/Entry.php, packages/php/src/Manifest.php, packages/php/tests/EntryTest.php, packages/php/tests/ManifestTest.php, packages/preset-vue-2/package.json, packages/preset-vue-3/package.json, packages/webpack-config/package.json
- Use more robust collections for the PHP package (b8e5042)
=> [Hotfix] 4.0.6

package-lock.json, package.json, packages/demo/package.json, packages/webpack-config/bin/cli.js, packages/webpack-config/package.json, packages/webpack-config/src/build.js
- Fix exit code when an error occurred during build (93e3fc4)
=> [Hotfix] 3.1.3

packages/webpack-config/bin/cli.js, packages/webpack-config/src/build.js
- Fix exit code when an error occurred during build (a9d626b)
=> [Bugfix] Fix exit code when an error occurred during build

composer.json, package-lock.json, package.json, packages/demo/package.json, packages/demo/src/js/app.ts, packages/preset-vue-2/package.json, packages/preset-vue-3/package.json, packages/webpack-config/package.json, packages/webpack-config/src/dev.js, packages/webpack-config/src/presets/eslint.js, packages/webpack-config/src/utils/get-browsersync.js, scripts/update-composer-version.mjs
- Fix injecting HMR snippet automatically (8b9d3cc)
- Fix eslint preset not linting .ts files (0c1b9d6)
- Fix exit code when an error occured during build (#94)
=> [Release] 4.0.7

package-lock.json, package.json
- Revert usage of custom version of Terser Webpack plugin (1129dd1)
=> [Hotfix] 1.1.3

composer.json, package-lock.json, package.json, packages/demo/package.json, packages/preset-vue-2/package.json, packages/preset-vue-3/package.json, packages/webpack-config/package.json, packages/webpack-config/src/webpack.base.config.js
- Fix ESM files in Node modules imported as strings (83ee13f)
=> [Hotfix] 4.2.1

composer.json, package-lock.json, package.json, packages/demo/package.json, packages/demo/src/css/app.scss, packages/demo/src/css/tailwind-base.css, packages/demo/src/js/Counter.vue, packages/preset-markdown/package.json, packages/preset-prototyping/package.json, packages/preset-vue-2/package.json, packages/preset-vue-3/package.json, packages/webpack-config/package.json, packages/webpack-config/src/build.js, packages/webpack-config/src/watch.js, packages/webpack-config/src/webpack.base.config.js, packages/webpack-config/src/webpack.dev.config.js, packages/webpack-config/src/webpack.prod.config.js
- Fix imports for `webpack-merge` (0c94569)
- Fix a bug where absolute URL in CSS files could not be resolved (cceedab)
- Improve watch command performance (b725511)
- Improve dev server performance (9108472)
- Use a browserslist query as target (e72bd02)
- Improve error logs (5c5d41a)
=> [Hotfix] 5.0.1

README.md, packages/demo/meta.config.js, packages/preset-markdown/README.md, packages/preset-markdown/src/index.js, packages/preset-prototyping/README.md, packages/preset-prototyping/src/index.js, packages/preset-vue-2/README.md, packages/preset-vue-2/src/index.js, packages/preset-vue-3/README.md, packages/preset-vue-3/src/index.js
- Add named exports to presets packages (#125)
=> [Feature] Add named exports to presets packages

packages/webpack-config/src/index.js
- Add named exports for Webpack's plugins (#129)
=> [Feature] Add exports for Webpack's plugins

packages/preset-markdown/src/index.d.ts, packages/preset-prototyping/src/index.d.ts, packages/preset-vue-2/src/index.d.ts, packages/preset-vue-2/src/index.js, packages/preset-vue-3/src/index.d.ts, packages/webpack-config/src/presets/index.d.ts
=> [Feature] Add types

packages/webpack-config/bin/cli.js
The command will create a symlink pointing to the given path in the `node_modules` folder.
```
$ meta link path/to/src --alias @ 
You can now use "@/" as an alias for the "path/to/src/" folder.
```
This allows alias usage without having to configure all tools: ESLint, Webpack, TypeScript, etc.
Example usage with both `app.js` and `component.js` files in the `path/to/src` folder:
```js
// app.js
import Component from '@/component.js';
```
=> [Feature] Add a `link` command to easily create import aliases

CHANGELOG.md, composer.json, eslint.config.js, package-lock.json, package.json, packages/demo/package.json, packages/preset-markdown/package.json, packages/preset-prototyping/package.json, packages/preset-vue-2/package.json, packages/preset-vue-3/package.json, packages/webpack-config/bin/cli.js, packages/webpack-config/package.json
- ⚠️ Remove the `meta link` command ([d255afe](https://github.com/studiometa/webpack-config/commit/d255afe))
=> [Release] 6.0.1

CHANGELOG.md, composer.json, package-lock.json, package.json, packages/demo/package.json, packages/preset-markdown/package.json, packages/preset-prototyping/package.json, packages/preset-vue-2/package.json, packages/preset-vue-3/package.json, packages/webpack-config/package.json
- Fix a dependency conflict ([629b170](https://github.com/studiometa/webpack-config/commit/629b170))
=> [Release] 6.0.2

CHANGELOG.md, composer.json, package-lock.json, package.json, packages/demo/package.json, packages/preset-markdown/package.json, packages/preset-prototyping/package.json, packages/preset-vue-2/package.json, packages/preset-vue-3/package.json, packages/webpack-config/package.json
- Fix a dependency conflict ([fcdf8bb](https://github.com/studiometa/webpack-config/commit/fcdf8bb))
=> [Hotfix] 5.3.1

CHANGELOG.md, composer.json, package-lock.json, package.json, packages/demo/package.json, packages/preset-markdown/package.json, packages/preset-prototyping/package.json, packages/preset-vue-2/package.json, packages/preset-vue-3/package.json, packages/webpack-config/package.json, packages/webpack-config/presets.js, packages/webpack-config/src/webpack.base.config.js
- Fix presets import not being resolved by ESLint ([aaf48e6](https://github.com/studiometa/webpack-config/commit/aaf48e6))
- Fix a bug where modules could not be found ([5d7bdca](https://github.com/studiometa/webpack-config/commit/5d7bdca))
=> [Hotfix] 5.3.2

CHANGELOG.md, package-lock.json, packages/preset-vue-2/README.md, packages/preset-vue-2/package.json, packages/preset-vue-2/src/index.d.ts, packages/preset-vue-2/src/index.js, packages/preset-vue-3/README.md, packages/preset-vue-3/src/index.d.ts, packages/preset-vue-3/src/index.js
- Add support for options for the Vue 2 preset
=> [Feature] Add suppport for options for the Vue presets

CHANGELOG.md, composer.json, package-lock.json, package.json, packages/demo/package.json, packages/preset-markdown/package.json, packages/preset-prototyping/package.json, packages/preset-vue-2/package.json, packages/preset-vue-3/package.json, packages/webpack-config/package.json
- Fix CJS files being incorrectly transformed to ESM ([#172](https://github.com/studiometa/webpack-config/pull/172), [e4cccc2](https://github.com/studiometa/webpack-config/commit/e4cccc2))
=> [Release] 6.2.1

CHANGELOG.md, package-lock.json, packages/demo/package.json, packages/preset-prototyping/package.json, packages/preset-prototyping/src/index.js, packages/preset-prototyping/src/loaders/twig-html-loader.js, packages/preset-prototyping/src/presets/twig.js, packages/preset-vue-3/package.json, packages/webpack-config/package.json, packages/webpack-config/src/dev.js
- Migrate twig-html-loader to ESM ([#174](https://github.com/studiometa/webpack-config/pull/174), [4f43408](https://github.com/studiometa/webpack-config/commit/4f43408))
- Update dependencies ([#174](https://github.com/studiometa/webpack-config/pull/174), [bc6e99b](https://github.com/studiometa/webpack-config/commit/bc6e99b))
- Update demo dependencies ([#174](https://github.com/studiometa/webpack-config/pull/174), [7c4bf9e](https://github.com/studiometa/webpack-config/commit/7c4bf9e))
- Update preset-prototyping dependencies ([#174](https://github.com/studiometa/webpack-config/pull/174), [3da5f22](https://github.com/studiometa/webpack-config/commit/3da5f22))
- Update preset-vue-3 dependencies ([#174](https://github.com/studiometa/webpack-config/pull/174), …
=> [Feature] Update dependencies

.github/workflows/release.yml, composer.json, package-lock.json, package.json, packages/demo/package.json, packages/preset-markdown/package.json, packages/preset-prototyping/package.json, packages/preset-tailwindcss-4/package.json, packages/preset-vue-2/package.json, packages/preset-vue-3/package.json, packages/webpack-config/package.json
- Fix release GitHub action ([c65cee1](https://github.com/studiometa/webpack-config/commit/c65cee1))
=> [Release] 6.3.1

.github/workflows/tests.yml, CHANGELOG.md, composer.json, package-lock.json, package.json, packages/demo/package.json, packages/php/src/Manifest.php, packages/php/tests/ManifestTest.php, packages/preset-markdown/package.json, packages/preset-prototyping/package.json, packages/preset-tailwindcss-4/package.json, packages/preset-vue-2/package.json, packages/preset-vue-3/package.json, packages/webpack-config/package.json, phpstan.neon
- Replace exceptions by warnings ([fe283af](https://github.com/studiometa/webpack-config/commit/fe283af))
=> [Release] 6.3.4
